package kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales;

import java.util.ArrayList;
import java.util.List;


import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.StringKey;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.SupportedLocale;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsAR;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsDA;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsDE;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsEN;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsEN_AU;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsEN_GB;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsES;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsES_MX;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsFR;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsHE;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsIS;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsIT;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsJA;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsKO;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsMS;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsNB;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsNL;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsPL;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsPT;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsPT_BR;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsRU;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsSV;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsTH;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsTR;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsZH_HANS;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsZH_HANT;
import kz.airbapay.apay_android.ui.pages.card_reader2.i18n.locales.LocalizedStringsZH_HANT_TW;

// Class autogenerated!  Do not modify.
// Generated on 2014-12-10 11:29:25.185885 via script:
// /Users/twhipple/Documents/buffalo/lib-i18n/i18n/script/generate_android_i18n.py -java_src_path src/ -java_gen_path gen/ -stringkey_path io/card/payment/i18n/ -strings_path ../strings/projects/card.io/strings/ --strict

public class LocalizedStringsList {
    public static final List<SupportedLocale<StringKey>> ALL_LOCALES = new ArrayList<>();

    static {
        ALL_LOCALES.add(new LocalizedStringsAR());
        ALL_LOCALES.add(new LocalizedStringsDA());
        ALL_LOCALES.add(new LocalizedStringsDE());
        ALL_LOCALES.add(new LocalizedStringsEN());
        ALL_LOCALES.add(new LocalizedStringsEN_AU());
        ALL_LOCALES.add(new LocalizedStringsEN_GB());
        ALL_LOCALES.add(new LocalizedStringsES());
        ALL_LOCALES.add(new LocalizedStringsES_MX());
        ALL_LOCALES.add(new LocalizedStringsFR());
        ALL_LOCALES.add(new LocalizedStringsHE());
        ALL_LOCALES.add(new LocalizedStringsIS());
        ALL_LOCALES.add(new LocalizedStringsIT());
        ALL_LOCALES.add(new LocalizedStringsJA());
        ALL_LOCALES.add(new LocalizedStringsKO());
        ALL_LOCALES.add(new LocalizedStringsMS());
        ALL_LOCALES.add(new LocalizedStringsNB());
        ALL_LOCALES.add(new LocalizedStringsNL());
        ALL_LOCALES.add(new LocalizedStringsPL());
        ALL_LOCALES.add(new LocalizedStringsPT());
        ALL_LOCALES.add(new LocalizedStringsPT_BR());
        ALL_LOCALES.add(new LocalizedStringsRU());
        ALL_LOCALES.add(new LocalizedStringsSV());
        ALL_LOCALES.add(new LocalizedStringsTH());
        ALL_LOCALES.add(new LocalizedStringsTR());
        ALL_LOCALES.add(new LocalizedStringsZH_HANS());
        ALL_LOCALES.add(new LocalizedStringsZH_HANT());
        ALL_LOCALES.add(new LocalizedStringsZH_HANT_TW());
    }
}
